# Generated by Django 3.1.4 on 2020-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_auto_20201219_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippets',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click the above link to view the snippet', max_length=255),
            preserve_default=False,
        ),
    ]
