# Generated by Django 3.1.4 on 2020-12-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_auto_20201222_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Uncategorised', max_length=255),
        ),
    ]
