# Generated by Django 3.1.4 on 2020-12-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0016_auto_20201222_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='commenter_name',
        ),
    ]
