# Generated by Django 3.1.4 on 2020-12-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_auto_20201222_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blogpost_connected',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
    ]
