# Generated by Django 3.1.4 on 2020-12-23 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_auto_20201223_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.TextField(default='user1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
