# Generated by Django 3.1.4 on 2021-01-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_auto_20201223_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
