# Generated by Django 3.1.4 on 2021-01-03 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0023_auto_20210103_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 9, 26, 10, 37538, tzinfo=utc)),
        ),
    ]
